apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: postgres

resources:
  - namespace.yaml
  - configmap.yaml
  - operator-service-account-rbac.yaml
  - postgres-operator.yaml
  - api-service.yaml
